### ISSUE TITLE
Discuss about replacing OpenTab by CloseTab

### ISSUE THREAD

**Issue by blfpd** [rotemdan/NanoGestures#1]
I usually don’t need a mouse gesture for opening a tab, because I have to reach for the keyboard to type the search/URL anyway.

What do you think about replacing it by closing the tab?

**Comment by rotemdan** [comment]
Hi, thanks for trying out the extension. It's still very new (although I've been testing it personally for several months). Only today I've managed to get somewhat reasonable functionality in Linux (which I've never tried to run the extension in before, since I mostly use Windows).

Since I'm actively working on this right now I'll try to give a bit more background, so future users can get a better understanding on what this extension is all about:

# Some background
The main reason for writing the extension was because Firefox converted to become WebExtensions-only in 57 and I needed mouse gestures really badly, and no good solution was available. So I tried to write the simplest extension that would fit my personal needs (which are very basic).

It turned out that it was possible to get a reasonably good result, that's lightweight and responsive (at least when is possible to run it -- Not being able to use it in the new tab page is a huge disadvantage and there is nothing I can do about it). It also turned out that it was technically possible to get gestures detected even before the page fully loads (and even before the `DOMContentLoaded` event).

In my own, personal style of gesture browsing I prefer to only make very quick and subtle mouse movements. This naturally excludes multi-directional gestures that requires say, drawing 'L' like shapes.

This (relatively strict) constraint basically limits the possibilities. Since 'back' and 'forward' gestures are basically a must (left and right).  Only two others practically remain: up, and down.

I chose 'up' to open a new tab and 'down' to reload current one (similar to 'slide down' to reload gesture in mobile browsers). However, in practice I don't use these very frequently (or at least not as frequently as back-forward).

I've just been reading the "Firefox" reddit channel, and noticed people were mentioning using a 'close tab' gesture frequently. I did not consider a gesture for that because it seems like closing the current tab would commonly change the active tab to an arbitrary tab, and in that case, the user would need to reach to the tab panel anyway -- to select a different tab (assuming the kind of people who use gestures have lots of open tabs). Also because it feels a bit 'risky' if the entire tab accidentally closed due to a very subtle unintended gesture (though it can be restored).

However, since other people's styles might be different than mine. There's no reason not to support it. I'll probably add it as an option some point in the future (though it wouldn't be a high priority at first).

I feel, though, a 'new tab' gesture is actually handy if one plans to immediately start typing in the address bar (it saves the need to move the cursor to the tab area) -- again it is a **huge** disadvantage that the gestures cannot be used in the new tab page! I'm personally annoyed by this a lot -- when navigating backwards, up until the new tab page and then getting 'stuck' because I can't move forward with a gesture.

# Some experimental ideas

There's an alternative way to address (some of) the possible scenarios where the user wants to 'close' (or at least 'leave') the current tab, _but not reach for the tab bar_.

In my own browsing I noticed I'd frequently open a link in a new tab, read it, and then instinctively try to 'navigate backwards' using a gesture to go back to the original page. However the gesture wouldn't work since I opened it in a new tab.

What if the 'navigate backward' and 'navigate forward' gestures could be optionally extended (the option would be off by default) by the following rough set of rules:

1. If the user tries to navigate backwards, and
2. The page is first in the history of the current tab, and
3. The opener tab, and page (one where the original link came from) is still open:

Change the active tab to the opener tab.

A parallel ruleset can work for the forward gesture, though it might prove to be less important.

Just some thoughts. Again, thanks for stopping by. I'm still working on this..

**Comment by rotemdan** [comment]
Other alternative ideas:

How about:

* `ctrl` + drag left to switch to left tab.
* `ctrl` + drag right to switch to right tab.
* `ctrl` + drag down to close current tab (sort of like 'thumbs down' for the tab).
* `ctrl` + drag up to [unspecified at the moment].

Being able to navigate quicly between tabs, it also makes sense to also have the ability to close the current tab (and since `ctrl` is pressed it would be less prone to accidents).

Now in light of this, having an unmodifed gesture to close current tab would be wasteful, since it would be probably be natural to have it in the 'tab navigation' context as well (i.e. when `ctrl` or some other key is pressed down).

_(Just a note: I guess the discussion is only about the defaults. Ultimately everything would be configurable, it might just take a little more time until that happens, as I try not to spend too much time on side projects)_

**_Edit: since we can't have gestures in the new tab page (and other special pages), these will be a serious problem for this kind of tab navigation if one ore more of the tabs has them as the current URL. I guess it is possible to skip them though, but it might appear a bit unexpected in some situations._**

**Comment by blfpd** [comment]
I’m glad that you wrote this plugin and you described your needs!
I agree with you with a lot of points.

I was using FireGestures a lot, and turned to smartUp Gestures which was the only one that worked.

I’m using Linux, I can confirmed that the mouseup flag flipped. :ok_hand: 

Concerning my needs:
- I don’t really need New Tab because I reach for the keyboard anyway.
- I don’t need a gesture for opening a link in a new tab as I middle click the link.
- I don’t need at my work the Previous/Back gestures as there is as my mouse have those buttons.
- I frequently use the refresh gesture, as I’m a Web developer.
- I frequently use the close gesture as I’m using and opening to much tab than I should.
- So I like to have a way to switch tabs, I’m using a lot of Previous Tab / Next Tab gestures

Conclusion:
- Your defaults are fine
- I could live with 4 gestures
- Could you adapt the settings to customize the actions per gesture?

**Comment by rotemdan** [comment]
Thanks for stopping by again. I did create an Ubuntu VM to test it under Linux, though I use it sporadically and can't leave it open all the time as I don't have enough memory on my machine, so it's good to know someone is testing it under Linux. I have no way to test it under macOS though.

Everything would eventually be configurable. The "hard" part -- of actually making the gesture detection work reliably, is basically done. Adding options and customization is comparably easy. 

The main obstacles are actually not related to the gestures themselves, but with dealing with the limitation of the WebExtension platform:

* For example. Say I support gestures for previous/next tab navigation, and one of the tabs has `about:newtab` open, and another has, say `about:addons` or `about:config` etc.  The tab navigation would get "stuck" in those tabs since there is no way for me to detect gestures on those pages.

* Another example: Since there is currently no way to query the history of an individual tab (see [this bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1378651)). I can't even know what page a navigation gesture would lead to. If that was available I could possibly cancel the 'back' gesture if the previous page was `abou:newtab` or similar (or alternatively delete the tab history entry altogether, though that would probably be a thing for a separate extension).

**Comment by blfpd** [comment]
I’m aware of the limitations of WebExtensions concerning pages like `about:*` and http://addons.mozilla.org/ and it looks like a WONTFIX for Mozilla.

So for the moment I just deal with it `¯\_(ツ)_/¯`

**Comment by rotemdan** [comment]
Version `0.3.0` is now released. There are many changes. Including:

* Full customization of all gestures.
* Several new possible actions (activate left tab, activate right tab, close tab, undo close tab).
* Possibility to skip special pages (`about:*` etc) when navigating between tabs.
* `ctrl` key modified gestures.
* Any options changed instantly update in all existing pages (no need to reload).

This eventually took about 10-12 total hours of work to achieve. Without the ability to test unpacked extensions in Chrome (along with `async/await` and `webextension-polyfill`) it would probably have taken much longer.

Since there are many changes and the general level of complexity of the extension has increased, it's important to get feedback quickly. I decided to push the changes early since it seems to be generally functioning (did not test under `Linux`/`macOS` though).

Please let me know if you encounter any issue.
