### ISSUE TITLE
Show trail when gesture is intercepted

### ISSUE THREAD

**Issue by apiraino** [rotemdan/NanoGestures#14]
Hi,

I like your extension so far: simple and effective, thank you!

It could nice to add a visual clue when the extension is tracking pixels (something like [an old extension did](http://loadion.com/ii/4727727043_6b3e133caa.jpg)).

Opinions?

**Comment by rotemdan** [comment]
Thanks for trying out the extension.

Since the currently supported gestures are only simple left, right, up, down drags, I'm not personally sure if trails would be a great fit. As an alternative I was considering some sort of semi-transparent 'Circle' menu.

Here's a random (unrelated) example image I found on google images, just to illustrate the concept:

![24069ecb5b9799791c9db7f504d843a7](https://user-images.githubusercontent.com/8589488/40008280-9b860770-57a7-11e8-9dfc-4e92eb2973a0.png)

Since the actions can be customized, it would mean finding a distinct icon for each possible action and dynamically drawing it in the circle based on the current setting (and active modifier key).

This can, of course, be achieved someday but I can't really see that happening within the next 6 months-year or so since currently my time is very limited (I'm concentrating only on the most critical bugs/features at a rate of about one per month on average).

**Comment by apiraino** [comment]
> Since the currently supported gestures are only simple left, right, up, down drags, I'm not personally sure if trails would be a great fit

you do have a point

> dynamically drawing it in the circle based on the current setting

I've been playing [Crysys](https://lh6.googleusercontent.com/TvX8nqGTWH5Oq_9sPHRa33WBohJPKxV8xF9hsg97eImpvm9o3yJ-t1PT5mCew4pF04CT1SZDfTRrahAjqZUGgfDq1R4KuQsAf4Rc6_bOAL4lprojECw) way too much to not see a citation to the nanosuite menu there :-)

Jokes aside, If I understood what you mean, I think choosing the gesture from a popup menu would be a bit cumbersome. The gesture should be executed in a blink of an eye through a muscle memory reflex (and again you're right here in keeping is lean and minimal).

Thanks for your time!

**Comment by rotemdan** [comment]
It may be useful for new users and those who are new to mouse gestures in general. The circle can be made very small (e.g. no more than, say 3-5 times larger than the cursor itself) and almost fully transparent.

More experienced users, I believe, who probably use very quick small movements may find it unnecessary though and would probably disable it. That's why I keep it as a low priority possible future enhancement.
